### PR TITLE
fix: timestamp include genesis delay

### LINKED ISSUE #16: SetConstraintsTooLate even it is 3 slots away
```
8cfc601351b0927b5cb }, preferences: ValidatorPreferences { filtering: Regional, trusted_builders: None, header_delay: true } } }])                                                                                                                                       
2024-10-16T15:04:12.286457Z  INFO helix_housekeeper::housekeeper: head_slot=843616 update_latency_ms=1                                                                                                                                                                   
2024-10-16T15:04:12.312971Z  INFO helix_housekeeper::housekeeper: updated proposer duties epoch_from=26363 num_duties=3                                                                                                                                                  
2024-10-16T15:04:12.314538Z  INFO helix_housekeeper::chain_event_updater: Processing payload attribute event head_slot=843616 payload_attribute_slot=843617 payload_attribute_parent=0x49aa6d6fd37f11b90d9a6842119401cac359d8abfcf526c3eae608f00b1878c3                  
2024-10-16T15:04:12.314903Z DEBUG helix_api::builder::api: randao=0xb2ebe7bd45e9f0d09af7a5c0b30e2b1a35da26103efc7cb4c71809d6cdfb432f timestamp=1729091064                     
2024-10-16T15:04:13.729846Z DEBUG helix_api::constraints::api: request_id=ad7bcef6-f9e6-435b-b68e-de364a87a0b3 event="get_preconfers_for_epoch" head_slot=843616 request_ts=1729091053729769772
2024-10-16T15:04:13.807106Z DEBUG helix_api::constraints::api: found elected gateway request_id=ad7bcef6-f9e6-435b-b68e-de364a87a0b3 num_preconfers_fetched=2 trace=GetGatewayTrace { receive: 1729091053729769772, gateway_fetched: 1729091053807069716 }
2024-10-16T15:04:22.617463Z  INFO helix_api::proposer::api: request_id=58af487e-9a69-4ab1-92ed-80671dca60c6 event="set_constraints" head_slot=843616 request_ts=1729091062616181430 request_slot=843618 num_constraints=1
2024-10-16T15:04:22.621000Z  WARN helix_api::proposer::api: validation failed request_id=58af487e-9a69-4ab1-92ed-80671dca60c6 err=SetConstraintsTooLate { ns_into_slot: 46616181430, cutoff: 8000000000 }                                                                
2024-10-16T15:04:23.024564Z  INFO helix_api::proposer::api: request_id=42d2ef42-e3d8-4227-92f5-83d496fb621a event="set_constraints" head_slot=843616 request_ts=1729091063023028660 request_slot=843618 num_constraints=1                              
2024-10-16T15:04:23.027561Z  WARN helix_api::proposer::api: validation failed request_id=42d2ef42-e3d8-4227-92f5-83d496fb621a err=SetConstraintsTooLate { ns_into_slot: 47023028660, cutoff: 8000000000 }
2024-10-16T15:04:23.415883Z  INFO helix_api::proposer::api: request_id=41c2c230-1637-4a9c-9931-d8e9565b88ca event="set_constraints" head_slot=843616 request_ts=1729091063415186319 request_slot=843618 num_constraints=1
2024-10-16T15:04:23.419063Z  WARN helix_api::proposer::api: validation failed request_id=41c2c230-1637-4a9c-9931-d8e9565b88ca err=SetConstraintsTooLate { ns_into_slot: 47415186319, cutoff: 8000000000 }                                              
2024-10-16T15:04:23.809149Z  INFO helix_api::proposer::api: request_id=10031030-82b2-4443-b89f-97e211952fe9 event="set_constraints" head_slot=843616 request_ts=1729091063807525670 request_slot=843618 num_constraints=1                              
2024-10-16T15:04:23.813038Z  WARN helix_api::proposer::api: validation failed request_id=10031030-82b2-4443-b89f-97e211952fe9 err=SetConstraintsTooLate { ns_into_slot: 47807525670, cutoff: 8000000000 }
2024-10-16T15:04:24.003857Z  INFO helix_housekeeper::chain_event_updater: Processing payload attribute event head_slot=843616 payload_attribute_slot=843618 payload_attribute_parent=0x49aa6d6fd37f11b90d9a6842119401cac359d8abfcf526c3eae608f00b1878c3                  
2024-10-16T15:04:24.004194Z DEBUG helix_api::builder::api: randao=0xb2ebe7bd45e9f0d09af7a5c0b30e2b1a35da26103efc7cb4c71809d6cdfb432f timestamp=1729091076
2024-10-16T15:04:24.083282Z  INFO helix_housekeeper::chain_event_updater: Processing head event head_slot=843617                                                                                                                                                         
2024-10-16T15:04:24.083511Z  INFO helix_housekeeper::housekeeper: process_new_slot is_new_block=true prev_head_slot=843616 head_slot=843617 
```

### LINKED ISSUE #17: Helix does't consider genesis delay when sanity check
for helix timestamp sanity check

https://github.com/lu-bann/helix/blob/046f7404418957d6c8b1c2b506ae5618360cad4e/crates/api/src/builder/api.rs#L1649-L1652

It doesn't consider genesis delay in network config like below

https://github.com/Commit-Boost/helder-devnets/blob/master/network-configs/devnet-0/metadata/config.yaml#L13

The real timestamp is always 60 second diff causing sanity check failed

### PR DESCRIPTION
**Pull request by zsluedem**
fix #17 #16 

## Summary by CodeRabbit

- **New Features**
	- Introduced a new method for block submission (`submit_block_v2`) with enhanced optimistic processing capabilities.
	- Added a function to retrieve the genesis time, improving timestamp accuracy in slot management.

- **Bug Fixes**
	- Enhanced error handling in payload decoding and header submission processes.

- **Improvements**
	- Refined logging and checks for duplicate block hashes and payload delivery status.
	- Updated calculations for slot management to improve temporal accuracy.
	- Improved validation logic for block submissions, ensuring compliance with regional filtering preferences.

### CODE REVIEW

File: crates/api/src/builder/api.rs [hunk 1]
```diff
@@ -1646,7 +1646,7 @@ fn sanity_check_block_submission(
     payload_attributes: &PayloadAttributesUpdate,
     chain_info: &ChainInfo,
 ) -> Result<(), BuilderApiError> {
-    let expected_timestamp = chain_info.genesis_time_in_secs + (bid_trace.slot * chain_info.seconds_per_slot);
+    let expected_timestamp = chain_info.genesis_time_in_secs + (bid_trace.slot * chain_info.seconds_per_slot) + chain_info.context.genesis_delay;
```
Comment (chirag-bgh) [inline crates/api/src/builder/api.rs]: I think we can use this instead: 
https://github.com/lu-bann/taiyi/blob/9382993fc17b1256c067ddbfd861ce9a23dd7673/crates/preconfer/src/preconf_api/mod.rs#L63

Comment (zsluedem) [reply crates/api/src/builder/api.rs]: Do you mean it would fail for Holesky if using current implementation?

Comment (chirag-bgh) [reply crates/api/src/builder/api.rs]: Yeah it would fail for all testnets. 

> `genesis_time` = `min_geneisis_time` + `genesis_delay`

this holds true only for testnets, not mainnet

Comment (zsluedem) [reply crates/api/src/builder/api.rs]: Make perfect sense!!

File: crates/api/src/lib.rs [hunk 2]
```diff
@@ -16,3 +18,10 @@ pub mod test_utils;
 mod grpc {
     include!(concat!(env!("OUT_DIR"), "/gossip.rs"));
 }
+
+pub fn get_genesis_time(chain_info: &ChainInfo) -> u64 {
+    match chain_info.context.genesis_time() {
+        Ok(genesis_time) => genesis_time,
+        Err(_) => chain_info.genesis_time_in_secs + chain_info.context.genesis_delay,
```
Comment (chirag-bgh) [inline crates/api/src/lib.rs]:
```suggestion
        Err(_) => chain_info.context.min_genesis_time + chain_info.context.genesis_delay,
```

**Review by chirag-bgh — APPROVED** [review]
LGTM
